version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
        - "${APP_PORT}"
    expose:
       - "${APP_PORT}"

  # postgress:
  #   ports:
  #     -
  #   environment:
  #     - name=value
